language: java

jdk:
    - openjdk8

build:
    ci:
        - ./gradlew buildWithWeb

    post_ci:
        - ./ci/copy-test-results.sh

    on_success:
        - curl -v $DEPLOY_URL

    on_failure:
        - ./ci/copy-test-results.sh