env:
    - secure: s2WOkFjFFlJjhwIuq4Vt30Yd0EozROwSn8sHCE7N+4b9PWpet01eTBlPeDiKcF87MaD+dEaoKhSKiIjgNQmsEbmrYCStbHYYcjvkwc0t4zl6offj7LCLqozbUx2IglmMyIpU8m9SMNDDf+mi3WvozC8SaY1AorRMxa8lNEtI8PQ+Q8rN9blGMD8iP69qWj2/+Z6wkjf1JTLTwbjoMUVKMe1TgIuaqIi/EWZqqmADNNRw/tozbhReKALeQFeblyorc8yJSHNFnOae59tGuvqebOBNxnjTW5uG0X41M12OmKMyF212/U8d4DefnR4jpF4VjoAvz+tgmCc3Ml4I0Xd1dA==

language: java

jdk:
    - openjdk8

build:
    ci:
        - ./gradlew build

    post_ci:
        - ./ci/copy-test-results.sh

    on_success:

        - if [[ "$BRANCH" == "master" &&  "$IS_PULL_REQUEST" = false && "$IS_FORK" = false ]]; then aws s3 sync $SHIPPABLE_BUILD_DIR/api/build/libs "s3://dovydasvenckus-artifacts" --region "eu-west-3" fi;

    on_failure:
        - ./ci/copy-test-results.sh