env:
    - secure: TEPTKrz5RZyT1g5mscSwDoNgT8vhx3vOc/ubLSC10GOzcws+o32BisgKFpu/Pd06wTcbjCe8oJ55CyX3zbV3gy9OewsIIDm93I/AUy6pKFoZhSgoz4rpm68CZJMiF/xiqCL5MV+AFaSzJOr77Cl73bxrrtDLRfwFG9dw9ssDw754j5cdVU4xEgiCB4+wRhcNz68skzRIS3KtleOgusFhLY8m4/bxzLr0FdxPZyuq/NibbyYC9N7c4e+565wufclKJUlt158/Bqvok+uci+er1Z8kQ9VeqsjzDi9a4CevR4L9KrheiJSci0GounMM1dDnwe9UsKXYwT44L/tILnWR1g==

language: java

jdk:
    - openjdk8

build:
    ci:
        - ./gradlew buildWithWeb

    post_ci:
        - ./ci/copy-test-results.sh

    on_success:
        - curl -v $TIME_TRACKER_DEPLOY_URL

    on_failure:
        - ./ci/copy-test-results.sh