spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      dialect: ${DB_DIALECT}

cors:
  allow: ${CORS_ALLOW}

rest:
  security:
    issuer-uri: ${AUTH_ISSUER_URI}

security:
  oauth2:
    resource:
      id: ${AUTH_CLIENT_ID}
      token-info-uri: ${rest.security.issuer-uri}/protocol/openid-connect/token/introspect
      user-info-uri: ${rest.security.issuer-uri}/protocol/openid-connect/userinfo
      jwt:
        key-value: ${AUTH_KEY}
