version: "3.7"
services:
  time-tracker-db:
    image: postgres:11-alpine
    environment:
      - POSTGRES_USER=time_tracker
      - POSTGRES_PASSWORD=super-secret-pass
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  authorization-server:
    image: jboss/keycloak:8.0.0
    network_mode: "host"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/dev-realm.json
    volumes:
      - ./keycloak-realm/time-tracker-realm.json:/tmp/dev-realm.json